import React from "react";
import { FaSquareRootAlt } from "react-icons/fa";
import Btn from "./Btn";
export default function ScientificButtonKeyboard({ operationHandler }) {
  return (
    <div className="scientific-keyboard">
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"Rad"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"Deg"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"x!"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"Inv"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"sin"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"In"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"pi"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"cos"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"log"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"e"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"tan"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={<span>&#8730;</span>}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"Ans"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"EXP"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"x^y"}
        backgroundColor={"#dadce0"}
      />
      <Btn
        operationHandler={operationHandler}
        btnTextContent={"="}
        backgroundColor={"#4285f4"}
      />
    </div>
  );
}
